/*-
 * Unsolvable Binary Word Matching
 * Copyright (C) 2016 Jonas Prellberg
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package uniol.matcher;

/**
 * Interface for different matcher implementations that can detect unsolvable
 * binary words. A word is unsolvable if it cannot be generated by a free Petri
 * net.
 */
public interface UnsolvableBinwordMatcher {

	/**
	 * Returns if the given binary word is unsolvable by a free Petri net.
	 *
	 * @param word
	 *                a binary word over the alphabet {a, b}
	 * @return true, if the word is unsolvable
	 */
	boolean isUnsolvableBinaryWord(String word);

}

// vim: ft=java:noet:sw=8:sts=8:ts=8:tw=120
